// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"backend/api/admin"
	"backend/internal/logic"
	"backend/internal/service"
)

type ControllerV1 struct{
	fs *service.FileService
	aal *logic.AdminAuthLogic
	arl *logic.AdminRoleLogic
	al *logic.AdminLogic
	cl *logic.ConfigLogic
}

func NewV1() admin.IAdminV1 {
	return &ControllerV1{
		fs: service.NewFileService(),
		aal: logic.NewAdminAuthLogic(),
		arl: logic.NewAdminRoleLogic(),
		al: logic.NewAdminLogic(),
		cl: logic.NewConfigLogic(),
	}
}
