// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// adminsDao is the data access object for the table tb_admins.
// You can define custom methods on it to extend its functionality as needed.
type adminsDao struct {
	*internal.AdminsDao
}

var (
	// Admins is a globally accessible object for table tb_admins operations.
	Admins = adminsDao{internal.NewAdminsDao()}
)

// Add your custom methods and functionality below.
