// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// adminRolesDao is the data access object for the table tb_admin_roles.
// You can define custom methods on it to extend its functionality as needed.
type adminRolesDao struct {
	*internal.AdminRolesDao
}

var (
	// AdminRoles is a globally accessible object for table tb_admin_roles operations.
	AdminRoles = adminRolesDao{internal.NewAdminRolesDao()}
)

// Add your custom methods and functionality below.
