// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// adminRoleAssocsDao is the data access object for the table tb_admin_role_assocs.
// You can define custom methods on it to extend its functionality as needed.
type adminRoleAssocsDao struct {
	*internal.AdminRoleAssocsDao
}

var (
	// AdminRoleAssocs is a globally accessible object for table tb_admin_role_assocs operations.
	AdminRoleAssocs = adminRoleAssocsDao{internal.NewAdminRoleAssocsDao()}
)

// Add your custom methods and functionality below.
