// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// adminAuthsDao is the data access object for the table tb_admin_auths.
// You can define custom methods on it to extend its functionality as needed.
type adminAuthsDao struct {
	*internal.AdminAuthsDao
}

var (
	// AdminAuths is a globally accessible object for table tb_admin_auths operations.
	AdminAuths = adminAuthsDao{internal.NewAdminAuthsDao()}
)

// Add your custom methods and functionality below.
