// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// configsDao is the data access object for the table tb_configs.
// You can define custom methods on it to extend its functionality as needed.
type configsDao struct {
	*internal.ConfigsDao
}

var (
	// Configs is a globally accessible object for table tb_configs operations.
	Configs = configsDao{internal.NewConfigsDao()}
)

// Add your custom methods and functionality below.
